Task 1 - sortStrings, pick, omit
js-tasks-ru/js-20210427_ifsogirl pull request #2
Opened 2021-05-01 14:53 UTC by IfSoGirl

2021-05-01 14:53 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-05-02 09:16 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const isEnglishA = /[a-zA-Z]/.test(a);
пожалуйста дайте пояснение логики которая здесь происходит.
Для чего нужно проверять что это `english` локаль?

2021-05-02 09:18 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    for (i = 0; (i < str1.length && i < str2.length && compareResult === 0); i++) {
чем данный подход лучше чем предыдущее решение через `localCompare`?

2021-05-02 09:18 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  fields.forEach(fieldName => {
good 👍

2021-05-02 09:18 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  Object.entries(obj).forEach(([fieldName, value]) => {
good 👍

2021-05-02 09:18 UTC, dosandk requested changes
необходимо дать ответы на вопросы

2021-05-02 15:52 UTC, IfSoGirl commented on 02-javascript-data-types/1-sort-strings/index.js
> +    for (i = 0; (i < str1.length && i < str2.length && compareResult === 0); i++) {
я хотела использовать только localeCompare (на строках целиком) и не сравнивать посимвольно, но не проходил последний тест со строкой Powerbank - она ставилась первой при сортировке (asc), а по тестам должна быть последней. Поэтому пришлось сравнивать посимвольно, и если символ английский, то ставить его после русского ( а не наоборот,как при обычной _сортировке)_

Причём в консоли браузера при сортировке через localeCompare "powebank" ставится на последнее место (как и ожидается в тесте). Очень странно.

2021-05-02 15:53 UTC, IfSoGirl commented on 02-javascript-data-types/1-sort-strings/index.js
> +    for (i = 0; (i < str1.length && i < str2.length && compareResult === 0); i++) {
Так-то конечно можно написать просто:

`export function sortStrings(arr, param = 'asc') {
  const result = [...arr];
  const isAscSorting = param === 'asc';
  result.sort((str1, str2) => {
    const compareResult = str1.localeCompare(str2, undefined, {
      caseFirst: 'upper'
    });

    return  isAscSorting? compareResult : -1 * compareResult;
  });
  
  return result;
}`

2021-05-02 15:58 UTC, IfSoGirl commented on 02-javascript-data-types/1-sort-strings/index.js
> +    for (i = 0; (i < str1.length && i < str2.length && compareResult === 0); i++) {
![image](https://user-images.githubusercontent.com/5743912/116819331-5d9e1b00-ab78-11eb-89d0-890f9e4bf2b8.png)

2021-05-04 09:41 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    for (i = 0; (i < str1.length && i < str2.length && compareResult === 0); i++) {
Для того чтобы `localeCompare` отрабатывал корректно, нужно передать локали, а не `undefined`.
Массив локалей: `['ru', 'en']`

2021-05-04 09:42 UTC, dosandk approved these changes

2021-05-04 09:42 UTC, merged